export const guptaEnvDTS = `export {};
declare global {
  let NUMBER_Null: 0;
  let STRING_Null: "";
  let DATETIME_Null: Date;
  let TRUE: true;
  let FALSE: false;
  let Window_Normal: unknown;
  let IDNO: unknown;
  let IDYES: unknown;
  let GET_SAME: unknown;
  let ROW_Selected: unknown;
  let ROW_MarkDeleted: unknown;
  let VALIDATE_Cancel: unknown;
  let VALIDATE_Ok: unknown;
  let DATE_RANGE: unknown;
  let TBL_FillAll: unknown;
  let TBL_Flag_SingleSelection: unknown;
  let TBL_Flag_SelectableCols: unknown;
  let nMultiLanguage: 0 | 1;
  let hSqlSelect: Symbol;
  let hWndItem: Symbol;
  let SqlDatabase: string;
  let ORDER_BY: string;
  let NO_WHERE: string;

  // SAL buildins (TODO: Find automatically all used Sal functions)
  let SalTblSetFlagsAnyRows: (...args: any[]) => any;
  let SalTblReset: (...args: any[]) => any;
  let SalTblDeleteRow: (...args: any[]) => any;
  let SalModalDialog: (...args: any[]) => any;
  let SalHideWindow: (...args: any[]) => any;
  let SalTblSetContext: (...args: any[]) => any;
  let SalTblInsertRow: (...args: any[]) => any;
  let SalTblSetFocusCell: (...args: any[]) => any;
  let SalClearField: (...args: any[]) => any;
  let SalDisableWindow: (...args: any[]) => any;
  let SalQuit: (...args: any[]) => any;
  let SalGetItemName: (...args: any[]) => any;
  let SalNumberToStrX: (...args: any[]) => any;
  let SalStrLeftX: (...args: any[]) => any;
  let SalEnableWindow: (...args: any[]) => any;
  let SalIsWindowVisible: (...args: any[]) => any;
  let SalAppEnable: (...args: any[]) => any;
  let SalAppDisable: (...args: any[]) => any;
  let SalEndDialog: (...args: any[]) => any;
  let SalSetFocus: (...args: any[]) => any;
  let SalBringWindowToTop: (...args: any[]) => any;
  let SalInvalidateWindow: (...args: any[]) => any;
  let SalUpdateWindow: (...args: any[]) => any;
  let SalSendMsg: (...args: any[]) => any;
  let SalGetWindowText: (...args: any[]) => any;
  let SalSetWindowText: (...args: any[]) => any;
  let SalPostMsg: (...args: any[]) => any;
  let SalCenterWindow: (...args: any[]) => any;
  let SalListAdd: (...args: any[]) => any;
  let SalMessageBox: (...args: any[]) => any;
  let SalDateWeekday: (...args: any[]) => any;
  let SalListSetSelect: (...args: any[]) => any;
  let SalStrToNumber: (...args: any[]) => any;
  let SqlPrepareAndExecute: (...args: any[]) => any;
  let SqlFetchNext: (...args: any[]) => any;
  let SalStatusSetText: (...args: any[]) => any;
  let SalCreateWindow: (...args: any[]) => any;
  let SalReportPrint: (...args: any[]) => any;
  let SalDestroyWindow: (...args: any[]) => any;
  let SalMessageBeep: (...args: any[]) => any;
  let SalWaitCursor: (...args: any[]) => any;
  let SalSetDefButton: (...args: any[]) => any;
  let SalStrScan: (...args: any[]) => any;
  let SalListPopulate: (...args: any[]) => any;
  let SalListInsert: (...args: any[]) => any;
  let SalListQuerySelection: (...args: any[]) => any;
  let SalFmtFormatDateTime: (...args: any[]) => any;
  let SalDateDay: (...args: any[]) => any;
  let SalDateMonth: (...args: any[]) => any;
  let SalDateYear: (...args: any[]) => any;
  let SalIsNull: (...args: any[]) => any;
  let SalStrLength: (...args: any[]) => any;
  let SalListQueryCount: (...args: any[]) => any;
  let SalTblPopulate: (...args: any[]) => any;
  let SalFmtFieldToStr: (...args: any[]) => any;
  let SalTblAnyRows: (...args: any[]) => any;
  let SalDlgSaveFile: (...args: any[]) => any;
  let SalStrUpperX: (...args: any[]) => any;
  let SalStrRightX: (...args: any[]) => any;
  let SalStrMidX: (...args: any[]) => any;
  let SalDateCurrent: (...args: any[]) => any;
  let SalSetMaxDataLength: (...args: any[]) => any;
  let SalFmtSetInputMask: (...args: any[]) => any;
  let SalStrRepeatX: (...args: any[]) => any;
  let SalStrTrim: (...args: any[]) => any;
  let SalListDelete: (...args: any[]) => any;
  let SalTblSetTableFlags: (...args: any[]) => any;
  let SalTblQueryContext: (...args: any[]) => any;
  let SalDateConstruct: (...args: any[]) => any;
  let SalArrayGetUpperBound: (...args: any[]) => any;

  // other global functions
  let HourGlass: (...args: any[]) => any;
  let VisWaitCursor: (...args: any[]) => any;
  let VisStrChoose: (...args: any[]) => any;
  let SqlCommit: (...args: any[]) => any;
  let SqlConnect: (...args: any[]) => any;
  let SqlDisconnect: (...args: any[]) => any;
  let SqlPrepare: (...args: any[]) => any;
  let SqlExecute: (...args: any[]) => any;
  let SqlExtractArgs: (...args: any[]) => any;
  let fnGetText: (...args: any[]) => any;
  let fnMultiMessageBoxA: (...args: any[]) => any;
  let fnClearMultiMesArray: (...args: any[]) => any;
  let SetWhereUnique: (...args: any[]) => any;
  let SetOrderBy: (...args: any[]) => any;
  let SetFocusField: (...args: any[]) => any;
  let SetChooseValuesX: (...args: any[]) => any;
  let GetBndVar: (...args: any[]) => any;

  // action triggers
  let PM_Create: any;
  let Task: any;

  // Message Box Flags
  let MB_Ok: number;
  let MB_OkCancel: number;
  let MB_IconExclamation: number;
  let MB_IconHand: number;
  let MB_IconQuestion: number;
  let MB_IconStop: number;
  let MB_YesNo: number;
  let MB_YesNoCancel: number;
  let MB_DefButton1: number;
  let MB_DefButton2: number;

  // "When" listeners
  let addListener: (event: string, cb: () => boolean) => void;
}
`;
