export const guptaEnvDTS = `declare var NUMBER_Null: 0;
declare var STRING_Null: "";
declare var DATETIME_Null: Date;
declare var TRUE: true;
declare var FALSE: false;
declare var Window_Normal: unknown;
declare var IDNO: unknown;
declare var IDYES: unknown;
declare var GET_SAME: unknown;
declare var ROW_Selected: unknown;
declare var ROW_MarkDeleted: unknown;
declare var VALIDATE_Cancel: unknown;
declare var VALIDATE_Ok: unknown;
declare var DATE_RANGE: unknown;
declare var TBL_FillAll: unknown;
declare var nMultiLanguage: 0 | 1;
declare var hSqlSelect: Symbol;
declare var hWndItem: Symbol;
declare var SqlDatabase: string;
declare var ORDER_BY: string;
declare var NO_WHERE: string;

// SAL buildins (TODO: Find automatically all used Sal functions)
declare var SalTblSetFlagsAnyRows: (...args: any[]) => any;
declare var SalTblReset: (...args: any[]) => any;
declare var SalTblDeleteRow: (...args: any[]) => any;
declare var SalModalDialog: (...args: any[]) => any;
declare var SalHideWindow: (...args: any[]) => any;
declare var SalTblSetContext: (...args: any[]) => any;
declare var SalTblInsertRow: (...args: any[]) => any;
declare var SalTblSetFocusCell: (...args: any[]) => any;
declare var SalClearField: (...args: any[]) => any;
declare var SalDisableWindow: (...args: any[]) => any;
declare var SalQuit: (...args: any[]) => any;
declare var SalGetItemName: (...args: any[]) => any;
declare var SalNumberToStrX: (...args: any[]) => any;
declare var SalStrLeftX: (...args: any[]) => any;
declare var SalEnableWindow: (...args: any[]) => any;
declare var SalIsWindowVisible: (...args: any[]) => any;
declare var SalAppEnable: (...args: any[]) => any;
declare var SalAppDisable: (...args: any[]) => any;
declare var SalEndDialog: (...args: any[]) => any;
declare var SalSetFocus: (...args: any[]) => any;
declare var SalBringWindowToTop: (...args: any[]) => any;
declare var SalInvalidateWindow: (...args: any[]) => any;
declare var SalUpdateWindow: (...args: any[]) => any;
declare var SalSendMsg: (...args: any[]) => any;
declare var SalGetWindowText: (...args: any[]) => any;
declare var SalSetWindowText: (...args: any[]) => any;
declare var SalPostMsg: (...args: any[]) => any;
declare var SalCenterWindow: (...args: any[]) => any;
declare var SalListAdd: (...args: any[]) => any;
declare var SalListAdd: (...args: any[]) => any;
declare var SalMessageBox: (...args: any[]) => any;
declare var SalDateWeekday: (...args: any[]) => any;
declare var SalListSetSelect: (...args: any[]) => any;
declare var SalStrToNumber: (...args: any[]) => any;
declare var SqlPrepareAndExecute: (...args: any[]) => any;
declare var SqlFetchNext: (...args: any[]) => any;
declare var SalStatusSetText: (...args: any[]) => any;
declare var SalCreateWindow: (...args: any[]) => any;
declare var SalReportPrint: (...args: any[]) => any;
declare var SalDestroyWindow: (...args: any[]) => any;
declare var SalMessageBeep: (...args: any[]) => any;
declare var SalWaitCursor: (...args: any[]) => any;
declare var SalSetDefButton: (...args: any[]) => any;
declare var SalStrScan: (...args: any[]) => any;
declare var SalListPopulate: (...args: any[]) => any;
declare var SalListInsert: (...args: any[]) => any;
declare var SalListQuerySelection: (...args: any[]) => any;
declare var SalFmtFormatDateTime: (...args: any[]) => any;
declare var SalDateDay: (...args: any[]) => any;
declare var SalDateMonth: (...args: any[]) => any;
declare var SalDateYear: (...args: any[]) => any;
declare var SalIsNull: (...args: any[]) => any;
declare var SalStrLength: (...args: any[]) => any;
declare var SalListQueryCount: (...args: any[]) => any;
declare var SalTblPopulate: (...args: any[]) => any;
declare var SalFmtFieldToStr: (...args: any[]) => any;
declare var SalTblAnyRows: (...args: any[]) => any;
declare var SalDlgSaveFile: (...args: any[]) => any;
declare var SalStrUpperX: (...args: any[]) => any;
declare var SalStrRightX: (...args: any[]) => any;
declare var SalStrMidX: (...args: any[]) => any;
declare var SalDateCurrent: (...args: any[]) => any;
declare var SalSetMaxDataLength: (...args: any[]) => any;
declare var SalFmtSetInputMask: (...args: any[]) => any;
declare var SalStrRepeatX: (...args: any[]) => any;
declare var SalStrTrim: (...args: any[]) => any;
declare var SalListDelete: (...args: any[]) => any;
declare var SalTblSetTableFlags: (...args: any[]) => any;
declare var SalTblQueryContext: (...args: any[]) => any;
declare var SalDateConstruct: (...args: any[]) => any;
declare var SalArrayGetUpperBound: (...args: any[]) => any;

// other global functions
declare var HourGlass: (...args: any[]) => any;
declare var VisWaitCursor: (...args: any[]) => any;
declare var VisStrChoose: (...args: any[]) => any;
declare var SqlCommit: (...args: any[]) => any;
declare var SqlConnect: (...args: any[]) => any;
declare var SqlDisconnect: (...args: any[]) => any;
declare var SqlPrepare: (...args: any[]) => any;
declare var SqlExecute: (...args: any[]) => any;
declare var SqlExtractArgs: (...args: any[]) => any;
declare var fnGetText: (...args: any[]) => any;
declare var fnMultiMessageBoxA: (...args: any[]) => any;
declare var fnClearMultiMesArray: (...args: any[]) => any;
declare var SetWhereUnique: (...args: any[]) => any;
declare var SetOrderBy: (...args: any[]) => any;
declare var SetFocusField: (...args: any[]) => any;
declare var SetChooseValuesX: (...args: any[]) => any;
declare var GetBndVar: (...args: any[]) => any;

// action triggers
declare var PM_Create: any;
declare var Task: any;

// Message Box Flags
declare var MB_Ok: number;
declare var MB_OkCancel: number;
declare var MB_IconExclamation: number;
declare var MB_IconHand: number;
declare var MB_IconQuestion: number;
declare var MB_IconStop: number;
declare var MB_YesNo: number;
declare var MB_YesNoCancel: number;
declare var MB_IconQuestion: number;
declare var MB_DefButton1: number;
declare var MB_DefButton2: number;

// "When" listeners
declare var addListener: (event: string, cb: () => boolean) => void;
`;
